### ISSUE TITLE
Type error while script execution

### ISSUE THREAD

**Issue by prawinsankar-ta** [jmitchell-99/follow-me-drone#1]
Hallo!
Have downloaded and installed dependencies as listed, but receiving Typo Error during execution of main.py file

![Screenshot from 2022-10-11 15-04-35](https://user-images.githubusercontent.com/44544565/195055052-d285bb1e-112d-4715-944e-90db9f108421.png)

Thanks in adavnce!

**Comment by jmitchell-99** [comment]
Hi,

I have not seen this error before, but I believe it is due to the
'ps_drone.py' file. This version of the ps_drone library only works with
python 2, and there should be a file called 'ps_drone3.py' in your
directory which is an updated version for python 3. You can download
'ps_drone3.py' from here: https://sourceforge.net/projects/ps-drone/files/

I would replace the 'ps_drone.py' file with 'ps_drone3.py' and then test it
again.

I have also just updated the README as I now see it takes you to a link
where only 'ps_drone.py' and not 'ps_drone3.py' is available, so thank you
for pointing this out to me!

Many thanks.

**Comment by prawinsankar-ta** [comment]
Hi @jmitchell-99 !
Thanks for reverting. I have got the file, I have resolved that error.
Currently, another error is popping out from Drone.startup function. (send.rawmsgs)
![Screenshot from 2022-10-11 19-53-08](https://user-images.githubusercontent.com/44544565/195118450-15ae81ad-3c18-49e6-a640-becfcb9e0d44.png)
 

Thanks again!

**Comment by jmitchell-99** [comment]
Hi,

I see these errors are from ps_drone3.py and unfortunately I didn't develop that library.

From what I can see it seems to be an issue with the connection to the drone itself. As there is no battery percentage printed I would assume there is no connection between the drone and PC? If you have connected to your drone via wi-fi and can run the ps_drone library outside of this repo, you should be able to use it.

Additionally, the library does provide some test files if you want to try out the drone's cameras or test moving the drone through python. These can be found here: http://www.playsheep.de/drone/downloads.html

If you run into any other issues with using the ps_drone library, I would look at this forum for help: https://sourceforge.net/p/ps-drone/blog/ . This is what helped me when I was first connecting the drone to my PC and controlling it through python.

If you can establish a connection between the drone and your PC, there should hopefully be no issues using this repo.

Many thanks.

**Comment by prawinsankar-ta** [comment]
Thanks for reaching out @jmitchell-99 !
